### ISSUE TITLE
Python error when running the analysis with the "boundaries" strategy

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/mapping_ecosystem_services#29] opened 2019-11-29 16:36 UTC
```
Traceback (most recent call last):
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mapping_ecosystem_services-master/mapping_ecosystem_services.py", line 560, in run
    ResultSet = srcDataSource.ExecuteSQL(sql, dialect='SQLite')
UnboundLocalError: local variable 'sql' referenced before assignment
```

it didn't happened before the implementation of the "centroids" strategy.

**Comment by lcalisto** [comment] 2019-11-29 18:07
Can you confirm in the last version? This should have been fixed by now. I can't reproduce it any more.

**Comment by gioman** [comment] 2019-11-29 18:10
> Can you confirm in the last version? This should have been fixed by now. I can't reproduce it any more.

@lcalisto yes, just download and installed the latest code.

**Comment by lcalisto** [comment] 2019-11-30 00:29
fixed! It was because of boundaries name change in https://github.com/NaturalGIS/mapping_ecosystem_services/commit/1fc52edfc11bac75fae72e3457e680ec7f6ef089 😃 Please test

**Comment by gioman** [comment] 2019-11-30 18:10
> fixed! It was because of boundaries name change in [1fc52ed](https://github.com/NaturalGIS/mapping_ecosystem_services/commit/1fc52edfc11bac75fae72e3457e680ec7f6ef089) smiley Please test

@lcalisto ah so it was my fault. Testing the fix is anyway now blocked by https://github.com/NaturalGIS/mapping_ecosystem_services/issues/8#issuecomment-560007027

**Closed as completed** 2019-11-30 22:50 UTC
Labels: bug
